// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ5eh2eh59uwfUV_2toTEKVNKMw0Ds0SE',
    appId: '1:261802239818:web:2d8e78f4b97dc9435bc3b3',
    messagingSenderId: '261802239818',
    projectId: 'smart-connect-58bff',
    authDomain: 'smart-connect-58bff.firebaseapp.com',
    storageBucket: 'smart-connect-58bff.appspot.com',
    measurementId: 'G-RQ0TDM2LYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApQJjbLzxAk-l_EtmVm_VYXcNXV41KIvc',
    appId: '1:261802239818:android:785bfb5355fc1ccb5bc3b3',
    messagingSenderId: '261802239818',
    projectId: 'smart-connect-58bff',
    storageBucket: 'smart-connect-58bff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlRFsidhNqqyQKvmefIeYncwqPQzeLf_Q',
    appId: '1:261802239818:ios:581bb6701b86f5105bc3b3',
    messagingSenderId: '261802239818',
    projectId: 'smart-connect-58bff',
    storageBucket: 'smart-connect-58bff.appspot.com',
    iosBundleId: 'com.info.masscommunication.massCommunication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlRFsidhNqqyQKvmefIeYncwqPQzeLf_Q',
    appId: '1:261802239818:ios:581bb6701b86f5105bc3b3',
    messagingSenderId: '261802239818',
    projectId: 'smart-connect-58bff',
    storageBucket: 'smart-connect-58bff.appspot.com',
    iosBundleId: 'com.info.masscommunication.massCommunication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ5eh2eh59uwfUV_2toTEKVNKMw0Ds0SE',
    appId: '1:261802239818:web:0f95477980ca0d1c5bc3b3',
    messagingSenderId: '261802239818',
    projectId: 'smart-connect-58bff',
    authDomain: 'smart-connect-58bff.firebaseapp.com',
    storageBucket: 'smart-connect-58bff.appspot.com',
    measurementId: 'G-0RS9E5KNXB',
  );
}
